pipeline{
    agent any
    environment{
        credentials="e532f9cb-47df-49b5-9bae-769de56c1481"
    }
    stages{
        stage("K8 cluster launch"){
            steps{
                withCredentials([file(credentialsId:env.credentials, variable: 'GC_KEY')]){
                    sh """
                        export GOOGLE_APPLICATION_CREDENTIALS=$GC_KEY
                        cd k8-cluster
                        terraform init
                        terraform plan
                        terraform apply -auto-approve
                        """
                }
            }
        }
        stage("K8 pod launch"){
            steps{
                withCredentials([file(credentialsId:env.credentials, variable: 'GC_KEY')]){
                    sh """
                        export GOOGLE_APPLICATION_CREDENTIALS=$GC_KEY
                        cd k8-cluster/k8-pod
                        terraform init
                        terraform plan
                        terraform apply -auto-approve
                        """
                }
            }
        }
    }
    post{
        //always
        //success
        //stable
        //unstable
        //failure
        always{
        cleanWs()
        }
    }
}