pipeline{
    agent any
    stages{
        stage ("docker creation")
        {
            steps{
               sh"""
               cd Docker
               sudo docker build -t myapp .
                sudo docker tag myapp:latest  us.gcr.io/clean-yew-297908/app:latest
               """
            }
        }
        stage ("Upload image")
        {
            steps{
            withCredentials([file(credentialsId:"e532f9cb-47df-49b5-9bae-769de56c1481", variable: 'GC_KEY')]){
                  sh """. ${JENKINS_HOME}/workspace/airflow-\${JOB_BASE_NAME}-$BUILD_NUMBER/bin/activate
                    cat '$GC_KEY' | sudo docker login -u _json_key --password-stdin https://us.gcr.io
                    sudo gcloud auth activate-service-account --key-file='$GC_KEY'
                    sudo gcloud auth configure-docker
                    sudo docker push us.gcr.io/clean-yew-297908/app:latest """
              }
           }
        }
    }
}